on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Publish binaries on release

jobs:
  build:
    name: Publish binaries
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build project
        run: |
          cargo build --release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/ntfy-run
          asset_name: ntfy-run-amd64
          tag: ${{ github.ref }}
          overwrite: true
